# api settings
api:
  version: v1.0

# server settings
server:
  port: 8081
  servlet:
    context-path: /bbq

# spring settings
spring:
  # redis settings
  redis:
    database: 0         # Redis数据库索引（默认为0）
    host: localhost     # Redis服务器地址
    port: 6379          # Redis服务器连接端口
    password:           # Redis服务器连接密码（默认为空）
    lettuce:            # 区别于jedis实现方式
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8     # 连接池中的最大空闲连接 默认 8
        min-idle: 0     # 连接池中的最小空闲连接 默认 0
  # database settings
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bbq?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5      #初始化大小
      minIdle: 5          #最小值
      maxActive: 20       #最大值
      maxWait: 60000      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      timeBetweenEvictionRunsMillis: 60000    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      minEvictableIdleTimeMillis: 300000      #配置一个连接在池中最小生存的时间

# mybatis settings
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


